### ISSUE TITLE
No dist folder

### ISSUE THREAD

**Issue by maroofsaeed** [trendier-ai/Ti.DrawerLayout#1]
Hi Sir,

Thanks for creating this awesome module. I have some few questions as i am using your source code in eclipse to build this module but it failed to build saying:

Drawer.java uses or overrides a deprecated API.

Can you please send the compiled module zip file or help to sort the errors?

Waiting for your reply

Regards,
Maroof Saeed
maroof.saeed@gmail.com

**Comment by metacortex** [comment]
I compiled in command line:

check this for how to compile titanium module in command line
http://docs.appcelerator.com/titanium/3.0/#!/guide/Android_Module_Development_Guide-section-29004945_AndroidModuleDevelopmentGuide-Building

and update android support v4 library jar file to the latest version in your titanium sdk installation.

for my case (osx)
~/Library/Application Support/Titanium/mobilesdk/osx/3.1.3.GA/android

I am using android-support-v4.jar of 554kb, and it compiles well.
(old version is 340kb)

**Comment by maroofsaeed** [comment]
Ok sir but can you please give a favour to compile this module so that I'
ll use it

**Comment by vagrantinoz** [comment]
release 1.0.1 >> com.tripvi.drawerlayout-android-1.0.1.zip
