### ISSUE TITLE
cannot built 

### ISSUE THREAD

**Issue by ankesh27** [trendier-ai/Ti.DrawerLayout#10]
Hey, can you please share the build zip file under dist. I am not able to build the same

**Comment by MatteoRosina** [comment]
@ankesh27 if you mean the release versions you can find them here https://github.com/Tripvi/Ti.DrawerLayout/releases

**Comment by ankesh27** [comment]
Why does it says that the module is not compatible with Current version of SDK as I am using Titanium SDK 3.2.0.GA and I suppose minimum SDK in the module is 3.1.X.GA

can you please help on this.

**Comment by ankesh27** [comment]
Version 1.0.1 crashes the app when I try to run a demo app with Titanium SDK 3.1.3 and higher
Version 1.0.2 doesnot even install (Attached is the issue)
![sserror](https://cloud.githubusercontent.com/assets/6457782/2953622/39f43712-da5f-11e3-94f4-d20fedf0bf79.png)

**Comment by metacortex** [comment]
@ankesh27 can you post your crash log? in full version

The module zip file in the release page have been compiled with 3.2.0.GA, and I checked it works well.

App crashing issue could be caused by android support library version issue.
please check this #2

**Comment by metacortex** [comment]
or can you try to install module by manually?

I'm not using Ti Studio.

Just unzip module zip file into  'modules/android' dir,
and add module entry to your tiapp.xml.

```
    <modules>
        <module platform="android" version="1.0.2">com.tripvi.drawerlayout</module>
    </modules>
```

**Comment by ankesh27** [comment]
@metacortex Yes that was the issue of android-support-v4. I just tried with SDK 3.2.3.GA and It worked. Same was the case with 1.0.2. Both are working now.
Thanks for a quick response.

Cheers!
