### ISSUE TITLE
Compiled version?

### ISSUE THREAD

**Issue by sschueller** [trendier-ai/Ti.DrawerLayout#2]
Is there a compiled version of this module available for Ti SDK 3.2.0?

Thanks

**Comment by ricardoalcocer** [comment]
I was able to compile it but I'm still getting some errors.  I agree.  A compiled version would be ideal.

**Comment by metacortex** [comment]
https://github.com/Tripvi/Ti.DrawerLayout/releases

I am using this version(1.0.1) and have no problem with  3.2.0.GA.

Check android support library v4 version in the titanium sdk installation,
and update android support v4 library jar file to the latest version.

for osx
~/Library/Application Support/Titanium/mobilesdk/osx/3.2.0.GA/android

the file size of android-support-v4.jar is 554kb
(old version is 340kb)

I don't know why titanium have packaged old version of support library.

**Comment by manumaticx** [comment]
The new version is scheduled for the next minor release of titanium
https://jira.appcelerator.org/browse/TIMOB-15264

**Comment by sschueller** [comment]
@metacortex Thanks for the compiled version. I will tried it out when I get a chance,

@manumaticx  I thought the DrawrLayout and ActionBar are two different things? The DrawerLayout is the drag menu on the left like in the gmail app where the ActionBar is the top menu bar.

**Comment by manumaticx** [comment]
@sschueller yes. But they depend on the same Android Support Library. The ticket description is just a bit confusing.

**Comment by ricardoalcocer** [comment]
@metacortex, I updated the library on the SDKFolder/android...it was indeed the old one.  

Still, I'm getting an error at runtime with both your version, and the one I compile myself.  I'm using the sample code provided with the module.  In case it helps, this is the error:

[ERROR] TiApplication: (main) [24,24] Sending event: exception on thread: main msg:java.lang.VerifyError: com/tripvi/drawerlayout/Drawer; Titanium 3.2.0,2013/12/20 10:57,d9182d6
[ERROR] TiApplication: java.lang.VerifyError: com/tripvi/drawerlayout/Drawer
[ERROR] TiApplication:  at com.tripvi.drawerlayout.DrawerProxy.createView(DrawerProxy.java:45)
[ERROR] TiApplication:  at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:465)
[ERROR] TiApplication:  at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:451)
[ERROR] TiApplication:  at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:489)
[ERROR] TiApplication:  at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:473)
[ERROR] TiApplication:  at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:451)
[ERROR] TiApplication:  at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:568)
[ERROR] TiApplication:  at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:546)
[ERROR] TiApplication:  at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:303)
[ERROR] TiApplication:  at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:32)
[ERROR] TiApplication:  at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:451)
[ERROR] TiApplication:  at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:527)
[ERROR] TiApplication:  at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] TiApplication:  at android.app.Activity.performCreate(Activity.java:5104)
[ERROR] TiApplication:  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
[ERROR] TiApplication:  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
[ERROR] TiApplication:  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
[ERROR] TiApplication:  at android.app.ActivityThread.access$600(ActivityThread.java:141)
[ERROR] TiApplication:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
[ERROR] TiApplication:  at android.os.Handler.dispatchMessage(Handler.java:99)
[ERROR] TiApplication:  at android.os.Looper.loop(Looper.java:137)
[ERROR] TiApplication:  at android.app.ActivityThread.main(ActivityThread.java:5041)
[ERROR] TiApplication:  at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] TiApplication:  at java.lang.reflect.Method.invoke(Method.java:511)
[ERROR] TiApplication:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
[ERROR] TiApplication:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
[ERROR] TiApplication:  at dalvik.system.NativeStart.main(Native Method)

**Comment by metacortex** [comment]
@ricardoalcocer 
check android version (newer than android-10), ndk (android-ndk-r9c)
ant clean and rebuild.
check 'ant install' log messages whether correct version of 'android-support-v4.jar' is used in building process.

I think most of 'java.lang.VerifyError' runtime error occurs in case of mismatched library(jar)

**Comment by ricardoalcocer** [comment]
@metacortex Hi.  Thanks for the pointers.  However your instructions relate to building the module.  My error is at runtime on the actual Titanium app using your binary.  The app builds and gets pushed to the device/emulator, but crashes before showing the first screen and that error is displayed on the terminal.

**Comment by metacortex** [comment]
Yes. runtime error can be occurred.

1) If you compile module from source codes, DrawerLayer symbol exception will be raised byjavac compiler.

2) But in case you have imported as a compiled-module to titanium project, DrawerLayer symbol exception will be raised when android-support libray got referenced.

another method to check the library version is unpacking android apk.
