### ISSUE TITLE
Compiled module

### ISSUE THREAD

**Issue by rajeshg** [trendier-ai/Ti.DrawerLayout#20]
Hi,

Is there a compiled version of your module v1.1.1? The demo app seems to be using v1.0.1. So no luck there. 

Tried to get the module compiled from source on a Windows machine but the compiler seems to keep failing.

Any pointers would be great. Thanks.

**Comment by metacortex** [comment]
check releases
https://github.com/Tripvi/Ti.DrawerLayout/releases
