### ISSUE TITLE
Add hamburger (ActionBarDrawerToggle) in ActionBar

### ISSUE THREAD

**Issue by timanrebel** [trendier-ai/Ti.DrawerLayout#3]
Would it be possible to add support for the official hamburger button (the ActionBarDrawerToggle) in the Actionbar?

image: https://developer.android.com/design/media/navigation_drawer_indicator_big.png

url: https://developer.android.com/design/patterns/navigation-drawer.html

**Comment by metacortex** [comment]
maybe possible if titanium supports android.support.v7.app.ActionBarActivity
https://jira.appcelerator.org/browse/TIMOB-15021

For 3.2.0.GA, I don't think it is possible without customizing titanium sdk itself.
(especially considering android 2.X)

Currently I am using custom titanium View (looks like actionBar)
and I have implemented hamburger button animating with offset value in 'drawerslide' event.

**Comment by timanrebel** [comment]
Not a bad idea at all. Thanks!

**Comment by sschueller** [comment]
@timanrebel I added the hamburger to this actionbar: https://github.com/sschueller/actionbarclone/ . It still needs some tiding up but it works.

**Comment by metacortex** [comment]
@sschueller Cool

**Comment by ricardoalcocer** [comment]
I was able to hack the "hamburger icon" into the native ActionBar.  Clone this branch: https://github.com/ricardoalcocer/Ti.DrawerLayout-Demo-Alloy-App/tree/hamburger_hack

Basically I'm using a custom ActionBar Theme and replacing the default homeAsUp icon with ic_drawer.png.  It's a hack with it's own drawbacks (the icon is not animated and any other activity will have that icon instead of the up caret), but a cool hack nonetheless. 

I'll write a full blog post in the next couple days.

R

**Comment by ingo** [comment]
Note that TIMOB-15021 is now implemented in release 3.3.0, so you should be unblocked there

**Comment by ricardoalcocer** [comment]
Any chance this could be reopened, now that TIMOB-15021 was fixed?

**Comment by metacortex** [comment]
http://developer.android.com/training/implementing-navigation/nav-drawer.html#ActionBarIcon

It looks like that main Activity should be sub-classed.

I'm just trying to avoid it.
Although I think Titanium SDK level implementation will be more easier.

**Comment by metacortex** [comment]
just released 1.1.0

supporting native actionBar

**Comment by ricardoalcocer** [comment]
Thank you @metacortex .  Working for me with 3.3.0.  One question though, since Titanium now supports ActionBar Compat to bring the ActionBar to all Android version, does this means that this module will also work on all Android versions?

**Comment by metacortex** [comment]
Yes. I hope so.

Titanium 3.3.0 is implemented to use ActionBar and ActionBarActivity from support-library.

Currently minSdkVersion="10" and targetSdkVersion="14",
and I think minSdkVersion should be 7 or later.
