### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by asleson** [trendier-ai/Ti.DrawerLayout#31]
I managed to build Ti.DrawerLayout by following the instructions.  One thing not mentioned in the instructions that i had to do was download the Android NDK (I downloaded the latest, r10) and provide its path in build.properties.

After that I was able to build and publish the module.

However, when I attempted to try it out in a test project (I just copied the Alloy code shown) the app failed with the following error when the app launched:

```
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[WARN] :   V8Object: Runtime disposed, cannot set property 'userAgent'
[ERROR] :  art: dlopen("/data/app-lib/com.tecfiniti.drawerlayouttest-2/libcom.tripvi.drawerlayout.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__cxa_end_cleanup" referenced by "libcom.tripvi.drawerlayout.so"...
[ERROR] :  TiApplication: (KrollRuntimeThread) [128,128] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_end_cleanup" referenced by "libcom.tripvi.drawerlayout.so"...; Titanium 3.3.0,2014/07/11 12:36,787cd39
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_end_cleanup" referenced by "libcom.tripvi.drawerlayout.so"...
[ERROR] :  TiApplication:   at java.lang.Runtime.loadLibrary(Runtime.java:364)
[ERROR] :  TiApplication:   at java.lang.System.loadLibrary(System.java:533)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:114)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:81)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:175)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
```

Any idea what is wrong?  It seemed to compile OK so I don't know how to even start debugging it.  Or, can somebody provide a packaged module that is known to work?

Thank you!!!

**Comment by manumaticx** [comment]
@asleson Under [releases](https://github.com/Tripvi/Ti.DrawerLayout/releases) you can download the packaged module. Latest is [com.tripvi.drawerlayout-android-1.1.1.zip](https://github.com/Tripvi/Ti.DrawerLayout/releases/download/1.1.1/com.tripvi.drawerlayout-android-1.1.1.zip)

I have also uploaded a newer version in my fork: https://github.com/manumaticx/Ti.DrawerLayout/tree/master/dist

**Comment by asleson** [comment]
@manumaticx  After I posted the issue I stumbled onto your branch and downloaded the master, which included the package module.  I tried it out and it works.  Thank you!!!!

I didn't even notice the "Releases" tab on the master home page.  Thank you for pointing that out!
