### ISSUE TITLE
Window backgrounds get overridden?

### ISSUE THREAD

**Issue by Bradleycorn** [trendier-ai/Ti.DrawerLayout#32]
I setup a simple application based on the Usage example in the readme. It works fine ... But, if I specify a background image (or background color) for a window that contains a DrawerLayout, the background image/color is not shown on my window. Instead I always get a light gray background color. Is there something I need to do to allow my background color/image to come through? Set the DrawerLayout background to "transparent"?

**Comment by manumaticx** [comment]
Hi @Bradleycorn, I tested and reproduced the issue. I've also proposed a fix. In the meantime you can grab the updated module package from [my fork](https://github.com/manumaticx/Ti.DrawerLayout). Cheers!

**Comment by Bradleycorn** [comment]
Thanks @manumaticx and @metacortex !
