### ISSUE TITLE
Multiple navigation

### ISSUE THREAD

**Issue by ssenior45** [trendier-ai/Ti.DrawerLayout#6]
I've worked out how to open a new window when clicking the menu - let's call that win1, but when I then open win2 from win1, depending on how I do it, I either have no access to the menu from win2, or I can access the menu but I can't get back to win1 - the back button takes me out of the app.

My project is a clone of Ricardo's demo app with the only the following modifications:

**menu.js**

``` javascript
var args = arguments[0] || {};

var data=[];

for (i=0;i<=10;i++){
    var row=Alloy.createController('menurow').getView();
    data.push(row);
}

$.menuTable.data=data;

function doMenuClick(){
    // handle the click and close the drawer
    //Alloy.CFG.contentView.backgroundColor='#' + generateColor();
    var v = Alloy.createController('win1').getView();
    Alloy.CFG.contentView.add(v);
    Alloy.CFG.drawer.toggleLeftWindow();  
}

function generateColor(){
    return (function lol(m, s, c) {
                    return s[m.floor(m.random() * s.length)] +
                        (c && lol(m, s, c - 1));
                })(Math, '3456789ABCDEF', 4);
}
```

**win1.xml**

``` xml
Alloy>
    <Window id="win1" backgroundColor="blue">
        <Label id="label" onClick="doClick">Hello, World</Label>
    </Window>
</Alloy>
```

**win2.xml**

``` xml
<Alloy>
    <Window id="win2" backgroundColor="red">
        <Label id="label" onClick="doClick">Hello, World Again</Label>
    </Window>
</Alloy>
```

**Scenario1 - no access to the drawer menu from win2**

**win1.js**

``` javascript
function doClick(e) {
    alert('Clicked win1');

    var v = Alloy.createController('win2').getView();
    v.open();
}
```

**win2.js**

``` javascript
function doClick(e) {
    alert('Clicked win2');
    Alloy.CFG.drawer.toggleLeftWindow();     //<-- does NOT show the menu
}
```

**Scenario2 - access to the drawer menu from win2 but no way back to win1**

**win1.js**

``` javascript
function doClick(e) {
    alert('Clicked win1');

    var v = Alloy.createController('win2').getView();
    Alloy.CFG.contentView.add(v);
}
```

**win2.js**

``` javascript
function doClick(e) {
    alert('Clicked win2');
    Alloy.CFG.drawer.toggleLeftWindow();     //<-- does show the menu but no back to win1
}
```

Any ideas what I am doing wrong?

Thanks in advance,
Steve

**Comment by metacortex** [comment]
It is native behavior of android drawer layout to work like scenario 1 & 2.
(Like Gmail, Google+ ...)

For scenario1,
You can add drawer-layout-menu to win2 (and every window you want to use drawer menu).

or

For scenario2,
use custom androidback event handler that keeps the old view history and pop the last one when the back button is clicked.

**Comment by ssenior45** [comment]
Thanks for the response. I'm new to Android, and after a bit of playing around with the Google apps, you are correct - scenario 1 is the correct behaviour.
